"""add textbooks and linking

Revision ID: 34ca66154a7b
Revises: bd3ed1d9e69a
Create Date: 2025-12-27 13:55:55.239784

"""
from alembic import op
import sqlalchemy as sa


revision = '34ca66154a7b'
down_revision = 'bd3ed1d9e69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litres_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('formats', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('author_normalized', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_textbook_lookup', 'text_books', ['normalized_key', 'author_normalized'], unique=False)
    op.create_index('idx_textbook_price', 'text_books', ['price'], unique=False)
    op.create_index('idx_textbook_year', 'text_books', ['year'], unique=False)
    op.create_index(op.f('ix_text_books_author_normalized'), 'text_books', ['author_normalized'], unique=False)
    op.create_index(op.f('ix_text_books_id'), 'text_books', ['id'], unique=False)
    op.create_index(op.f('ix_text_books_litres_id'), 'text_books', ['litres_id'], unique=True)
    op.create_index(op.f('ix_text_books_normalized_key'), 'text_books', ['normalized_key'], unique=False)
    op.create_table('audiobook_textbook',
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['textbook_id'], ['text_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audiobook_id', 'textbook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiobook_textbook')
    op.drop_index(op.f('ix_text_books_normalized_key'), table_name='text_books')
    op.drop_index(op.f('ix_text_books_litres_id'), table_name='text_books')
    op.drop_index(op.f('ix_text_books_id'), table_name='text_books')
    op.drop_index(op.f('ix_text_books_author_normalized'), table_name='text_books')
    op.drop_index('idx_textbook_year', table_name='text_books')
    op.drop_index('idx_textbook_price', table_name='text_books')
    op.drop_index('idx_textbook_lookup', table_name='text_books')
    op.drop_table('text_books')
    # ### end Alembic commands ###
