"""init

Revision ID: 56b93f64f07a
Revises: 
Create Date: 2025-12-25 22:23:58.165796

"""
from alembic import op
import sqlalchemy as sa


revision = '56b93f64f07a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litres_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('formats', sa.JSON(), nullable=True),
    sa.Column('fragment_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audiobook_created', 'audiobooks', ['created_at'], unique=False)
    op.create_index('idx_audiobook_name_search', 'audiobooks', ['name'], unique=False)
    op.create_index('idx_audiobook_price', 'audiobooks', ['price'], unique=False)
    op.create_index(op.f('ix_audiobooks_id'), 'audiobooks', ['id'], unique=False)
    op.create_index(op.f('ix_audiobooks_litres_id'), 'audiobooks', ['litres_id'], unique=True)
    op.create_index(op.f('ix_audiobooks_name'), 'audiobooks', ['name'], unique=False)
    op.create_index(op.f('ix_audiobooks_slug'), 'audiobooks', ['slug'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    op.create_index(op.f('ix_authors_slug'), 'authors', ['slug'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['genres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('audiobook_author',
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audiobook_id', 'author_id')
    )
    op.create_table('audiobook_genre',
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audiobook_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiobook_genre')
    op.drop_table('audiobook_author')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_authors_slug'), table_name='authors')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_audiobooks_slug'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_name'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_litres_id'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_id'), table_name='audiobooks')
    op.drop_index('idx_audiobook_price', table_name='audiobooks')
    op.drop_index('idx_audiobook_name_search', table_name='audiobooks')
    op.drop_index('idx_audiobook_created', table_name='audiobooks')
    op.drop_table('audiobooks')
    # ### end Alembic commands ###
