"""add guides tables

Revision ID: 8a881594c8f8
Revises: 61e009e4ab87
Create Date: 2025-12-28 07:31:21.200658

"""
from alembic import op
import sqlalchemy as sa


revision = '8a881594c8f8'
down_revision = '61e009e4ab87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('md_file', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.create_index(op.f('ix_guides_slug'), 'guides', ['slug'], unique=True)
    op.create_table('guide_audiobook',
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guide_id', 'audiobook_id')
    )
    op.drop_index('ix_audiobook_author_audiobook_id', table_name='audiobook_author')
    op.drop_index('ix_audiobook_author_author_id', table_name='audiobook_author')
    op.drop_index('ix_audiobook_genre_audiobook_id', table_name='audiobook_genre')
    op.drop_index('ix_audiobook_genre_genre_id', table_name='audiobook_genre')
    op.drop_index('idx_audiobook_normalized_lookup', table_name='audiobooks')
    op.drop_index('ix_audiobooks_created_at', table_name='audiobooks')
    op.drop_column('audiobooks', 'normalized_key')
    op.drop_column('audiobooks', 'author_normalized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiobooks', sa.Column('author_normalized', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('normalized_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index('ix_audiobooks_created_at', 'audiobooks', ['created_at'], unique=False)
    op.create_index('idx_audiobook_normalized_lookup', 'audiobooks', ['normalized_key', 'author_normalized'], unique=False)
    op.create_index('ix_audiobook_genre_genre_id', 'audiobook_genre', ['genre_id'], unique=False)
    op.create_index('ix_audiobook_genre_audiobook_id', 'audiobook_genre', ['audiobook_id'], unique=False)
    op.create_index('ix_audiobook_author_author_id', 'audiobook_author', ['author_id'], unique=False)
    op.create_index('ix_audiobook_author_audiobook_id', 'audiobook_author', ['audiobook_id'], unique=False)
    op.drop_table('guide_audiobook')
    op.drop_index(op.f('ix_guides_slug'), table_name='guides')
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    op.drop_table('guides')
    # ### end Alembic commands ###
