"""init

Revision ID: bd3ed1d9e69a
Revises: 56b93f64f07a
Create Date: 2025-12-25 23:12:31.759253

"""
from alembic import op
import sqlalchemy as sa


revision = 'bd3ed1d9e69a'
down_revision = '56b93f64f07a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
